return {
  
    "ACDC.acwire",
    "APA.acwire",
    "Among Us.acwire",
    "Ancestor.acwire",
    "Anime Girl 2.acwire",
    "Anime Girl.acwire",
    "Assassins Creed.acwire",
    "Asuka.acwire",
    "Avatar.acwire",
    "Awp.acwire",
    "BO2.acwire",
    "BO3.acwire",
    "Banana.acwire",
    "Bar Open.acwire",
    "Bart Simpson 2.acwire",
    "Bart Simpson 3.acwire",
    "Bart Simpson.acwire",
    "Blood Globe.acwire",
    "BloodIdk.acwire",
    "Boo.acwire",
    "Box.acwire",
    "BoyFriend.acwire",
    "Bugatti Cheyron.acwire",
    "Bugatti Veyron.acwire",
    "Burger.acwire",
    "Chest.acwire",
    "Coca Cola.acwire",
    "CocaCola.acwire",
    "Coil.acwire",
    "Covid 19.acwire",
    "Deadpool.acwire",
    "Defaultio.acwire",
    "Deku.acwire",
    "Dino 3D.acwire",
    "Dino Venyx.acwire",
    "Discord.acwire",
    "DiscordWire.acwire",
    "Dogix.acwire",
    "Donkey.acwire",
    "Dr Stone.acwire",
    "Dragon.acwire",
    "Duck.acwire",
    "Ducky.acwire",
    "F15.acwire",
    "Family Guy.acwire",
    "Ferris Wheel.acwire",
    "FidgetSpinner.acwire",
    "Football.acwire",
    "FoxGirl.acwire",
    "French Alien.acwire",
    "Fuck my ass.acwire",
    "Gas Mask.acwire",
    "Greenday.acwire",
    "Hacker.acwire",
    "Hacker2.acwire",
    "Horse.acwire",
    "Jake the Dog.acwire",
    "KFC.acwire",
    "Karambit.acwire",
    "Luffy Wano Post Card.acwire",
    "MP5.acwire",
    "Marge Simpson.acwire",
    "McLovinIt.acwire",
    "Mina.acwire",
    "Mortal Kombat.acwire",
    "Naked Anime.acwire",
    "Nike Logo.acwire",
    "Obama.acwire",
    "Oddy.acwire",
    "Papa Smurf.acwire",
    "Pepe the Frog.acwire",
    "Pickup Truck.acwire",
    "Pico.acwire",
    "Pig.acwire",
    "Pink Floyd.acwire",
    "Pistol.acwire",
    "Plane.acwire",
    "Plane2.acwire",
    "Rainbow.acwire",
    "Rick.acwire",
    "Roblox 2.acwire",
    "Roblox.acwire",
    "Rocket.acwire",
    "Roxy.acwire",
    "Saitama.acwire",
    "School Bus.acwire",
    "Scorpion.acwire",
    "Shop.acwire",
    "Skull.acwire",
    "UNO Reverse.acwire",
    "Vapourwave.acwire",
    "Vegetables.acwire",
    "Venyx.acwire",
    "Watch Dog.acwire",
    "Watch Tower.acwire",
    "Xerneas.acwire",
    "Yeet.acwire",
    "Youtube.acwire",
    "Zoro Chibi.acwire",
    "Zoro.acwire",
  
};
